### ISSUE TITLE
Monthly calendar view is not showing all days

### ISSUE THREAD

**Issue by batadamnjanovic** [kizitonwose/CalendarView#232] opened 2020-10-28 22:56 UTC
Version: 0.4.5
Device: Xiaomi Mi A3, Android 10, 720x1560

When swiping through months, specifically when April is selected, calendar does not show all days. I've tried with `notifyMonthChanged(month: YearMonth)` but without success. Please advise.

Recording: https://drive.google.com/file/d/1fXa9UL3pae6B-SiUKEDGZ9-AJ9OB79WS/view

And an image:
![calendarbug](https://user-images.githubusercontent.com/22530295/97505009-55221900-1978-11eb-9c06-441acbe2de13.jpeg)

**Comment by kizitonwose** [comment] 2020-10-31 16:43
This has been fixed previously so I'm not sure why you're still experiencing the issue. It would be nice if you can let me know how to reproduce this.

**Comment by batadamnjanovic** [comment] 2020-11-03 15:58
@kizitonwose 
It looks like it is happening when I put a margin on a Calendar
```
android:layout_marginStart="20dp"
android:layout_marginEnd="20dp"
```

Without margin, it works. But design requires to set margin because of the arrows.

Do you have a suggestion how should I handle this?

**Comment by kizitonwose** [comment] 2020-11-04 09:08
Maybe use padding instead?

**Comment by batadamnjanovic** [comment] 2020-11-04 10:14
When using padding, calendar does not show all weeks, it has an offset. I've tried different combinations.
I managed to work on my device with margin=16dp, but who knows how it will work on other devices

**Comment by kizitonwose** [comment] 2020-11-06 11:03
A rather temporary fix would be to wrap the calendar in a framelayout and apply the margin or padding to the framelayout instead.

**Comment by batadamnjanovic** [comment] 2020-11-06 11:38
I've also tried that, but without success.

**Comment by batadamnjanovic** [comment] 2020-11-06 12:59
Device is Xiaomi Mi A3, Android 10

**Comment by batadamnjanovic** [comment] 2020-11-06 13:23
So, I've debugged more, and it turns out that it is working with margin **21dp**. Somehow margin **20dp** is a magic number :)). 
Resolutions that experience this problems are: 720x1560, 768x1280

**Comment by kizitonwose** [comment] 2020-11-08 14:18
Ok, this is quite hilarious. I don't even know what to do here.

**Comment by kizitonwose** [comment] 2020-11-08 14:20
So ...19 and 21... work fine on all devices but 20dp is where the issue happens?

**Comment by batadamnjanovic** [comment] 2020-11-08 17:04
Yes, and not on all devices :) I've tested on emulators and these two resolutions have the same problem: 720x1560, 768x1280

**Comment by batadamnjanovic** [comment] 2020-11-08 17:22
If you want to reproduce this, create a virtual device with 720x1560.
In CalendarUtils in `daysOfWeekFromLocale()` method, change the locale to be `WeekFields.of(Locale.UK).firstDayOfWeek`.
And on `com.kizitonwose.calendarview.CalendarView` set marginStart end marginEnd to 20dp.
And try again with 21dp, it will work :)

**Comment by batadamnjanovic** [comment] 2020-11-09 22:50
@kizitonwose 
Another thing. Months can have 4, 5 or 6 rows. Can I somehow know the number of rows in advance for the current month in order to smoothly animate calendar from weekly to monthly view?
![Screen Shot 2020-11-09 at 11 46 56 PM](https://user-images.githubusercontent.com/22530295/98605683-272cc500-22e6-11eb-9ed4-6c65b72f8173.png)

**Comment by kizitonwose** [comment] 2020-11-10 10:18
> I've tested on your Example1Fragment.
> 
> If you want to reproduce this, create a virtual device with 720x1560.
> In CalendarUtils in `daysOfWeekFromLocale()` method, change the locale to be `WeekFields.of(Locale.UK).firstDayOfWeek` - to set a Monday as a first day of week.
> And on `com.kizitonwose.calendarview.CalendarView` set marginStart and marginEnd to 20dp.
> And try again with 21dp, it will work :)

I'll take a look soon. Thankfully you have something that works temporarily.

**Comment by kizitonwose** [comment] 2020-11-10 10:22
> Another thing. Months can have 4, 5 or 6 rows. Can I somehow know the number of rows in advance for the current month in order to smoothly animate calendar from weekly to monthly view?


`val rowCount = calendarView.findFirstVisibleMonth()?.weekDays?.size`

**Comment by batadamnjanovic** [comment] 2020-11-10 15:12
> val rowCount = calendarView.findFirstVisibleMonth()?.weekDays?.size

It's not working as expected. Sometimes it returns wrong value for the row count

**Comment by kizitonwose** [comment] 2020-11-10 16:13
> It's not working as expected. Sometimes it returns a wrong value for the `rowCount`.

Could you explain further?

**Comment by Buddypas** [comment] 2020-11-18 13:40
The same thing happened to me, but calling notifyCalendarChanged in the month scroll listener fixed the issue for me. Also, since in its base the calendar is a RecyclerView, if you are toggling the visibility of views in a certain month they can get recycled and stay hidden in other months, so in the day binder init block make sure to set the proper visibility. Hope this helps.

**Comment by asthagarg2428** [comment] 2021-01-07 12:23
In Addition to above doubt, how to handle date selection? Like if we select another date, previous one should be deselected. Is there any in-build way to achieve this? @batadamnjanovic , @kizitonwose

**Comment by kizitonwose** [comment] 2021-01-11 18:07
I'm closing this issue as the main problem is addressed. The idea that 20dp breaks on a 720x1560 device is not something I want to investigate 😆

**Closed by kizitonwose** 2021-01-11 18:07 UTC
