### ISSUE TITLE
Bug with monthHeaderBinder

### ISSUE THREAD

**Issue by ru-alxr** [kizitonwose/CalendarView#40] opened 2019-08-06 14:00 UTC
Reproduce:

```
 <com.kizitonwose.calendarview.CalendarView
                android:id="@+id/calendarView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:cv_dayViewResource="@layout/item_calendar_day_layout"
                app:cv_orientation="horizontal"
                app:cv_scrollMode="paged"
                app:cv_hasBoundaries="false"
                app:cv_monthHeaderResource="@layout/item_month_header"
                app:cv_maxRowCount="6"/>
```

```
inner class MonthHeader : MonthHeaderFooterBinder<MonthViewContainer> {

        override fun bind(container: MonthViewContainer, month: CalendarMonth) {
            container.setName(month)
        }

        override fun create(view: View): MonthViewContainer = MonthViewContainer(view)
    }

```

CalendarMonth always the same.

**Comment by kizitonwose** [comment] 2019-08-07 12:10
You have `hasBoundaries` set to `false` so it's not that the header view is not updated but it's updated with the same value. Please set `hasBoundaries` to `true` unless you really want the boundaryless behavior.

**Comment by kizitonwose** [comment] 2019-08-10 09:19
Closing this as it works as intended.

**Closed by kizitonwose** 2019-08-10 09:19 UTC
