### ISSUE TITLE
monthScrollListener CalendarMonth

### ISSUE THREAD

**Issue by Shakezulla57** [kizitonwose/CalendarView#142] opened 2020-04-07 19:27 UTC
I'm implementing a month and week view switcher. Much like your Example 1 in the sample application.

I'm having issues with the `CalendarMonth` that gets returned from the `monthScrollListener`.

For reference if the calendar is on April week view and I'm transitioning back to the month view. The `monthScrollListener` will get called twice. The first time will be June 2019, the start month of the calendar, and then it will be called again with April. The issue is that we get this flashing label from the text being updated rapidly. Also I play with different configurations of the calendar the `CalendarMonth` returned in the `monthScrollListener` seems to be inconsistently June.

**Comment by kizitonwose** [comment] 2020-04-09 18:05
Indeed when `hasBoundaries` is set to `false`, the `month` value in the `CalendarMonth` is really not valid anymore because an index can contain several months. I guess the proper design would be to make this value optional so it's null in this case.  That would be a consideration for the next major iteration. 

Meanwhile, if you need the month value in this case, you can get it from the date passed in the `CalendarMonth` class. You can always check the first and last dates in the list to see if they are from different months and act accordingly.

For the issue with title blinking, I don't see it happening in example 1. Maybe you should explain further so I can reproduce.

**Comment by Shakezulla57** [comment] 2020-04-09 18:15
Thanks for the response. The blinking is just a bi-product of the textview being upated quickly from june to april from my example. But that should be a non-issue now as long as I can use the first/last dates list.

**Comment by kizitonwose** [comment] 2020-04-09 18:18
Okay then, Guess I can close this now. Let me know if you have any other issues.

**Closed by kizitonwose** 2020-04-09 18:18 UTC
