### ISSUE TITLE
NoSuchMethodError after migrating to 0.4.x

### ISSUE THREAD

**Issue by minarja1** [kizitonwose/CalendarView#209] opened 2020-09-01 18:19 UTC
Hello, 

I migrated to the latest version (0.4.3) and now I am getting the following error.
note: error only occurs in release build variant and might have something to do with latest version of Kotlin (1.4)

`Fatal Exception: java.lang.NoSuchMethodError: No virtual method lengthOfMonth()I in class Lj$/time/YearMonth; or its super classes (declaration of 'j$.time.YearMonth' appears in base.apk!classes2.dex)
       at com.kizitonwose.calendarview.model.MonthConfig$Companion.generateWeekDays$com_github_kizitonwose_CalendarView(MonthConfig.kt:187)
       at com.kizitonwose.calendarview.model.MonthConfig$Companion.generateBoundedMonths(MonthConfig.kt:57)
       at com.kizitonwose.calendarview.model.MonthConfig.<init>(MonthConfig.kt:23)
       at com.kizitonwose.calendarview.CalendarView.setup(CalendarView.kt:767)`

**Comment by kizitonwose** [comment] 2020-09-03 07:56
Interesting, not sure what the root cause could be. Maybe I need to update the deps in the library as well.

**Comment by kizitonwose** [comment] 2020-09-26 04:59
Updated a lot of dependencies in 0.4.4, kindly check if you still have this issue.

**Comment by kizitonwose** [comment] 2020-10-23 08:40
Guess I can close this. Let me know if it still happens.

**Closed by kizitonwose** 2020-10-23 08:40 UTC
