### ISSUE TITLE
Wrong number display

### ISSUE THREAD

**Issue by bakhus99** [kizitonwose/CalendarView#356] opened 2021-12-28 12:07 UTC
I have an issue with displaying date with  app:cv_maxRowCount="2"  it shows 21 instead of 28

![image](https://user-images.githubusercontent.com/44024437/147564742-37592d08-2172-46e1-9dcd-71825d4d122e.png)

**Comment by kizitonwose** [comment] 2022-01-23 11:10
Can I have a sample project where this can be reproduced?

**Comment by bakhus99** [comment] 2022-01-23 11:18
private val selectedDates = mutableSetOf<LocalDate>()
    private val dateFormatter = DateTimeFormatter.ofPattern("dd")
    private val dayFormatter = DateTimeFormatter.ofPattern("EEE")

    override fun getBinding(inflater: LayoutInflater) =
        ScreenBoadcastsByDateBinding.inflate(inflater)

    override fun initialize() {
        initRecycler()
        initView()
        initCalendar()
    }

 private fun initCalendar() {
        val dm = DisplayMetrics()
        val wm = requireContext().getSystemService(Context.WINDOW_SERVICE) as WindowManager
        wm.defaultDisplay.getMetrics(dm)
        binding.weekCalendar.apply {
            val dayWidth = (dm.widthPixels - 20.dp) / 7
            val dayHeight = (dayWidth * 1)
            daySize = Size(dayWidth, dayHeight)
        }

        class DayViewContainer(view: View) : ViewContainer(view) {
            val bind = ItemCalendarBinding.bind(view)
            lateinit var day: CalendarDay

            val parentView = ItemCalendarBinding.bind(view).parentView
            val dateText = ItemCalendarBinding.bind(view).dateText
            val dateNumber = ItemCalendarBinding.bind(view).dateNumber

            init {
                view.setOnClickListener {
                    if (day.owner == DayOwner.THIS_MONTH) {
                        if (selectedDates.contains(day.date)) {
                            selectedDates.remove(day.date)
                        } else {
                            selectedDates.add(day.date)
                        }
                        binding.weekCalendar.notifyDayChanged(day)
                    }
                }
            }

            fun bind(day: CalendarDay) {
                this.day = day
                bind.dateNumber.text = dateFormatter.format(day.date)
                bind.dateText.text = dayFormatter.format(day.date)
            }
        }

        binding.weekCalendar.dayBinder = object : DayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view)
            override fun bind(container: DayViewContainer, day: CalendarDay) {
                container.bind(day)
                container.day = day
                val parentView = container.parentView
                val dateText = container.dateText
                val dateNumber = container.dateNumber
                if (day.owner == DayOwner.THIS_MONTH) {
                    when {
                        selectedDates.contains(day.date) -> {
                            dateText.setTextColorRes(R.color.purple50)
                            dateNumber.setTextColorRes(R.color.purple)
                            parentView.setBackgroundResource(R.drawable.selected_day)
                        }
                        else -> {
                            dateText.setTextColorRes(R.color.white50)
                            dateNumber.setTextColorRes(R.color.white)
                            parentView.setBackgroundResource(R.drawable.calendar_rounded_corners)
                        }
                    }
                } else {
                    dateText.setTextColorRes(R.color.white50)
                    dateNumber.setTextColorRes(R.color.white)
                    parentView.setBackgroundResource(R.drawable.calendar_rounded_corners)
                }
            }
        }
        val currentMonth = YearMonth.now()

        binding.weekCalendar.setup(
            currentMonth,
            currentMonth.plusMonths(3),
            DayOfWeek.values().random()
        )
        binding.weekCalendar.scrollToDate(LocalDate.now())
    }

    @SuppressLint("ClickableViewAccessibility")
    private fun initView() {
        binding.apply {
            weekCalendar.addOnItemTouchListener(object : SimpleOnItemTouchListener() {
                override fun onInterceptTouchEvent(rv: RecyclerView, e: MotionEvent): Boolean {
                    return rv.scrollState == SCROLL_STATE_DRAGGING
                }
            })
            weekCalendar.setOnTouchListener { _, event ->
                event.action == MotionEvent.ACTION_MOVE
            }
        }
    }

XML

     <com.kizitonwose.calendarview.CalendarView
            android:id="@+id/weekCalendar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="4dp"
            android:layout_marginEnd="16dp"
            app:cv_dayViewResource="@layout/item_calendar"
            app:cv_hasBoundaries="false"
            app:cv_inDateStyle="none"
            app:cv_maxRowCount="2"
            app:cv_orientation="horizontal"
            app:cv_outDateStyle="none"
            app:cv_scrollMode="continuous" />

**Comment by kizitonwose** [comment] 2022-01-23 11:20
I cannot run the shared code. Please use the sample project. That makes it easy for me.

**Comment by bakhus99** [comment] 2022-01-23 11:58
> I cannot run the shared code. Please use the sample project. That makes it easy for me.

https://github.com/bakhus99/SampleForBug can you check pls why its cells are moving too?)

**Comment by kizitonwose** [comment] 2022-01-23 13:02
I looked at the sample, and the date is actually correct. It looks wrong because you have enabled `continuous` scroll mode and you are not showing the month info in the day views so it is impossible to tell what month has what number since the view does not settle on each item view like scroll mode is `paged`.

I have attached screenshots of your sample. The first one shows the "error" you explained, the second one shows the same view when you swipe to the left

<img src="https://user-images.githubusercontent.com/15170090/150679331-cf977be2-66ac-4bfc-a686-66f7d700c336.png" width="300">

<img src="https://user-images.githubusercontent.com/15170090/150679458-7ca0fd6b-8a4b-4750-9220-4c0162ad5b7f.png" width="300">

Of course, the week has Saturday as the first day because you disabled indates so the calendar cannot be padded accordingly. You can enable indates for the first month `app:cv_inDateStyle="firstMonth"` to fix this.

**Comment by bakhus99** [comment] 2022-01-23 13:45
Did you try to manually on your phone selecte 26 date as today's date?

**Comment by kizitonwose** [comment] 2022-01-23 13:47
I don't see how that makes a difference. As I said, the date is correct, it's just the placement when you scroll that makes it look wrong.

**Comment by bakhus99** [comment] 2022-01-23 13:55
Can i make it static then?

**Comment by kizitonwose** [comment] 2022-01-23 14:43
I don't understand. Can you explain better?

**Comment by bakhus99** [comment] 2022-01-23 15:30
I want the first day to be today

**Comment by kizitonwose** [comment] 2022-01-23 20:42
If you show the month information, then the context is not lost and you can keep the current logic. I'll close this issue as it is not from the library.

**Closed by kizitonwose** 2022-01-23 20:42 UTC

**Comment by bakhus99** [comment] 2022-01-24 05:22
![image](https://user-images.githubusercontent.com/44024437/150726441-ef4b8352-0aa3-462c-9aba-7d44682e7bcf.png)

Its from your example if you select today date as 26 this happen

**Comment by kizitonwose** [comment] 2022-01-24 08:11
The section actually looks like this, you have enabled continuous scrolling which allows the calendar to settle at any point. You can switch to "paged" scrolling so this does not happen.


<img src="https://user-images.githubusercontent.com/15170090/150745089-812b8989-17cd-46df-ba5e-c1539ea7cb33.png" width="300">
