### ISSUE TITLE
ERROR: Failed to resolve: com.github.kizitonwose:CalendarView:0.3.2

### ISSUE THREAD

**Issue by reuniware** [kizitonwose/CalendarView#119] opened 2020-01-29 15:10 UTC
Hello
I have created a basic project in Android Studio but cannot import this library.
The compiledSdkVersion is 28.
And I have well added the maven repository in the Project build.gradle.
And in the Module build.gradle I have added the following line in the dependencies section :
    implementation 'com.github.kizitonwose:CalendarView:0.3.2'

**Comment by repon85** [comment] 2020-01-29 20:00
Add the JitPack repository to your project level build.gradle:

allprojects {
 repositories {
    google()
    jcenter()
    maven { url "https://jitpack.io" }
 }
}

**Comment by reuniware** [comment] 2020-01-30 08:34
I've already done that initially...

**Comment by reuniware** [comment] 2020-02-03 11:28
I code in Kotlin, maybe that this is the issue ?

**Comment by repon85** [comment] 2020-02-03 11:58
> I code in Kotlin, maybe that this is the issue ?

I am also. I have not faced any problem

**Comment by reuniware** [comment] 2020-02-04 09:54
Ok, I'll try again... Thanks.

**Comment by kizitonwose** [comment] 2020-02-12 19:14
Closing this issue as it's not related to the library itself.

**Closed by kizitonwose** 2020-02-12 19:14 UTC

**Comment by mrwtaylor2009** [comment] 2020-02-29 22:53
Hi,
Unfortunately I'm actually having exactly the same issue as this.
I'm fairly new to android development but followed the exact steps as above so far and getting the same error message.
Please, any further suggestions?

**Comment by reuniware** [comment] 2020-03-02 09:58
I have still not resolved this issue...
I think that there is a problem with latest versions of Kotlin...
Not sure.

**Comment by kizitonwose** [comment] 2020-03-02 19:41
I have cleaned my gradle cache but was still able to install the library(0.3.2) without issues. Not exactly sure what setup you have so don't know how to help, unfortunately.

**Comment by Besong** [comment] 2020-04-12 04:28
The build.gradle file at the project level has two sides where  **maven { url ["http://jitpack.io"](http://jitpack.io)  }** could be placed. Make sure you place the library under the allprojects section like this:

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "http://jitpack.io" }
    }
}
This did it for me!.

**Comment by reuniware** [comment] 2020-05-02 10:21
Ok I'll try that. Thanks.

**Comment by dpatra** [comment] 2020-06-27 06:19
This is related to the project being in Kotlin, and used in Java

**Comment by reuniware** [comment] 2020-06-27 07:43
> This is related to the project being in Kotlin, and used in Java

Are you sure ? Because my project is in Kotlin.

**Comment by dpatra** [comment] 2020-06-27 11:23
Yes, I tried creating AAR out of your project and then add as a dependency module. Still it failed. 

If you could convert your project to a Java version; that would really help.

**Comment by yamankatby** [comment] 2020-09-22 15:21
same here

**Comment by Kapkwang** [comment] 2022-06-14 19:43
I'm in the process of implementing this library to a project and just encountered the same issue as seen below:

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.kizitonwose:CalendarView:<latest-version>.
<a href="Unable to resolve dependency for %27%3Aapp%40debug%2FcompileClasspath%27%3A Could not resolve com.github.kizitonwose%3ACalendarView%3A%3Clatest-version%3E.">[Show Details](https://github.com/kizitonwose/CalendarView/issues/Unable%20to%20resolve%20dependency%20for%20%27%3Aapp%40debug%2FcompileClasspath%27%3A%20Could%20not%20resolve%20com.github.kizitonwose%3ACalendarView%3A%3Clatest-version%3E.)</a>
Affected Modules: <a href="openFile:C:/Users/kapkw/AndroidStudioProjects/FeatureSandbox/[app](openfile:C:/Users/kapkw/AndroidStudioProjects/FeatureSandbox/app/build.gradle)/build.gradle">app</a>

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.kizitonwose:CalendarView:<latest-version>.
<a href="Unable to resolve dependency for %27%3Aapp%40debugAndroidTest%2FcompileClasspath%27%3A Could not resolve com.github.kizitonwose%3ACalendarView%3A%3Clatest-version%3E.">[Show Details](https://github.com/kizitonwose/CalendarView/issues/Unable%20to%20resolve%20dependency%20for%20%27%3Aapp%40debugAndroidTest%2FcompileClasspath%27%3A%20Could%20not%20resolve%20com.github.kizitonwose%3ACalendarView%3A%3Clatest-version%3E.)</a>
Affected Modules: <a href="openFile:C:/Users/kapkw/AndroidStudioProjects/FeatureSandbox/[app](openfile:C:/Users/kapkw/AndroidStudioProjects/FeatureSandbox/app/build.gradle)/build.gradle">app</a>

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.kizitonwose:CalendarView:<latest-version>.
<a href="Unable to resolve dependency for %27%3Aapp%40debugUnitTest%2FcompileClasspath%27%3A Could not resolve com.github.kizitonwose%3ACalendarView%3A%3Clatest-version%3E.">[Show Details](https://github.com/kizitonwose/CalendarView/issues/Unable%20to%20resolve%20dependency%20for%20%27%3Aapp%40debugUnitTest%2FcompileClasspath%27%3A%20Could%20not%20resolve%20com.github.kizitonwose%3ACalendarView%3A%3Clatest-version%3E.)</a>
Affected Modules: <a href="openFile:C:/Users/kapkw/AndroidStudioProjects/FeatureSandbox/[app](openfile:C:/Users/kapkw/AndroidStudioProjects/FeatureSandbox/app/build.gradle)/build.gradle">app</a>


Changing the line:

implementation 'com.github.kizitonwose:CalendarView:<latest-version>'

To:

implementation 'com.github.kizitonwose:CalendarView:1.0.4'

Resolved the issue for me. Hope this helps identify the root cause of the problem, but for now it seems I can carry on using the library.

Cheers.
