### ISSUE TITLE
CalendarView "flashes" when loading in a custom ConstraintLayout dialog view with guidelines

### ISSUE THREAD

**Issue by mcezat** [kizitonwose/CalendarView#69] opened 2019-10-16 17:21 UTC
I added the CalendarView in a ConstraintLayout which I set as the view in a DialogFragment. When the dialog is shown, you see the calendar but then the calendar flashes. Additionally if you scroll to the next month, that month also flashes. After the initial flash upon loading, it is not seen again (until a new instance of the dialog is created).

The CalendarView has its width and height set to "wrap_content" and the width is constrained to a start and end guideline widgets (to act as margin). The flash also occurs if you instead just add layout_margin attributes.

**Comment by kizitonwose** [comment] 2019-10-17 12:19
Could you kindly provide a sample project where I can replicate this issue?

**Comment by mcezat** [comment] 2019-10-23 16:27
Please see my changes in the fork of your repo for Example1. I changed it into a DialogFragment and made the base layout a ConstraintLayout instead of a LinearLayout.

https://github.com/mcezat/CalendarView/commit/8cffc6ffc16357ca4f86469b0713ffab828f002f

**Comment by kizitonwose** [comment] 2019-10-28 12:46
After much investigation, I can see that this is somewhat similar to the issue raised [here](https://github.com/kizitonwose/CalendarView/issues/6), in the sense that the payload is not delivered hence the entire month is reloaded which gives the blink effect. However, the suggested fix in that issue did not work in the example project you provided. What worked was to remove the item animator(`calendarView.itemAnimator = null`).

I'm not quite sure how to implement a permanent fix for this issue since I can't figure out why the `RecyclerView` behaves differently when in a ConstraintLayout.

**Comment by mcezat** [comment] 2019-10-28 22:12
@kizitonwose Please see my [PR](https://github.com/kizitonwose/CalendarView/pull/72). I see in other custom views around github that they were calling super.onMeasure() before their own custom logic. Moving that to the beginning indeed fixed the blink. I did a smoke test of your other sample calendars in the app and they all seemed fine.

**Comment by kizitonwose** [comment] 2019-11-02 14:39
> Please see my [PR](https://github.com/kizitonwose/CalendarView/pull/72). I see in other custom views around github that they were calling super.onMeasure() before their own custom logic. Moving that to the beginning indeed fixed the blink. I did a smoke test of your other sample calendars in the app and they all seemed fine.
> 

@mcezat Since the PR is closed, I guess the short term fix would be to not have it in a constraint layout, for now.

**Comment by AlexandreGorobets** [comment] 2020-01-28 07:37
Hello!

The simplest way for displaying the problem is to change **example_1_fragment.xml** with adding marginStart/marginEnd for CalendarView

For example:

`        <com.kizitonwose.calendarview.CalendarView
            android:id="@+id/exOneCalendar"
            android:layout_marginStart="30dp"
            android:layout_width="0dp"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            android:layout_height="wrap_content"
            app:cv_dayViewResource="@layout/example_1_calendar_day"
            app:cv_orientation="horizontal"
            app:cv_scrollMode="paged"
            app:layout_constraintTop_toTopOf="parent" />`

After that CalendarView.onMeasure will be called twice for every call of **notifyDayChanged** and condition for daySize will raise invalidateViewHolders() with full rebind of day items in recycler

**Comment by mirwisek** [comment] 2020-06-02 11:24
Definitely it's constraint layout and works fine with height set to `match_parent` inside it, but when changed to `wrap_content` or `0dp` the flash occurs.

**Comment by kizitonwose** [comment] 2020-06-11 18:01
After taking some time today to look into how ConstraintLayout measures children with `0dp`, I found that the measurement really happens twice, the first time with a size/spec of 0 and then the second time with the appropriate values.

So what happens is that when you reload a date, the calendar is invalidated and during the first pass(with 0 value) the calendar basically disappears and then reappears in the next pass, giving the blink effect. 

The initial fix was to ignore this initial measure pass which worked great but looking further into how RecyclerView measures itself, I noticed that we could benefit from setting `hasFixedSize` to `true` which was the initial workaround for this bug as seen [here](https://github.com/kizitonwose/CalendarView/issues/6#issuecomment-517917367) because reloading a date does not actually affect the calendar's size. This is also more efficient as the calendar is no longer invalidated when you reload a date hence no measurement happens at all.

This fix is in the [0.3.5](https://github.com/kizitonwose/CalendarView/releases/tag/0.3.5) release so I will be closing this issue.

**Closed by kizitonwose** 2020-06-11 18:01 UTC

**Comment by mirwisek** [comment] 2020-06-12 05:34
@kizitonwose  Great that you've figured it out

**Comment by victory316** [comment] 2020-06-24 09:03
> After much investigation, I can see that this is somewhat similar to the issue raised [here](https://github.com/kizitonwose/CalendarView/issues/6), in the sense that the payload is not delivered hence the entire month is reloaded which gives the blink effect. However, the suggested fix in that issue did not work in the example project you provided. What worked was to remove the item animator(`calendarView.itemAnimator = null`).
> 
> I'm not quite sure how to implement a permanent fix for this issue since I can't figure out why the `RecyclerView` behaves differently when in a ConstraintLayout.

Thanks for supporting great library. I was experiencing blink on change text inside the monthScrollListener, finally solved with setting itemAnimator to null :)
